//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "image_objects")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub image_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub object_id: String,
    #[sea_orm(
        belongs_to,
        from = "image_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub images: BelongsTo<super::images::Entity>,
    #[sea_orm(
        belongs_to,
        from = "object_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub objects: BelongsTo<super::objects::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
