//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "images")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub source_constellation: String,
    #[sea_orm(column_type = "Text")]
    pub source_page: String,
    #[sea_orm(column_type = "Text")]
    pub local_path: String,
    #[sea_orm(column_type = "Text")]
    pub sha256: String,
    pub width: i64,
    pub height: i64,
    #[sea_orm(column_type = "Text")]
    pub credit: String,
    pub score: i64,
    #[sea_orm(column_type = "Text")]
    pub metadata_json: String,
    #[sea_orm(has_one)]
    pub selections: HasOne<super::selections::Entity>,
    #[sea_orm(has_many, via = "image_objects")]
    pub objects: HasMany<super::objects::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
