//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "objects")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Double")]
    pub ra_deg: f64,
    #[sea_orm(column_type = "Double")]
    pub dec_deg: f64,
    #[sea_orm(column_type = "Text")]
    pub coordinate_frame: String,
    #[sea_orm(column_type = "Text")]
    pub object_type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub morphology: Option<String>,
    pub bibliography_count: i64,
    #[sea_orm(has_one)]
    pub object_distances: HasOne<super::object_distances::Entity>,
    #[sea_orm(has_many, via = "image_objects")]
    pub images: HasMany<super::images::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
