//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "object_distances")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub object_id: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Double", nullable)]
    pub distance_mpc: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub distance_million_ly: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub uncertainty_mpc: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub method: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub redshift: Option<f64>,
    #[sea_orm(column_type = "Text")]
    pub source_url: String,
    #[sea_orm(column_type = "Text")]
    pub metadata_json: String,
    #[sea_orm(
        belongs_to,
        from = "object_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub objects: BelongsTo<super::objects::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
