[package]
name = "web"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
axum = { version = "0.8.9", features = ["macros"] }
tokio = { version = "1.53.2", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
serde.workspace = true
serde_json.workspace = true
tower-http = { version = "0.7.1", features = ["trace", "fs"] }
chrono = { version = "0.4.45", features = ["serde"] }
ephemerust = "0.7.0"
sweph = "0.3.0"
strum_macros = "0.28.0"
strum = "0.28.0"
sea-orm = { version = "2.0.4", features = ["runtime-tokio", "sqlx-sqlite", "macros", "debug-print", "with-chrono"] }
